# -*- coding: utf-8 -*-
"""copyrights_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Daaj3PDRm3qJn6mMuIrqE-C1AGcj-3iJ
"""

import psycopg2
import pandas as pd
import json

def fetch_copyright_data():
    try:
        connection = psycopg2.connect(
            dbname="fossology",
            user="fossy",
            password="fossy",
            host="localhost",
            port="5432"
        )
        cursor =  connection.cursor()

        sql = """
        SELECT DISTINCT ON(copyright_pk, UT.uploadtree_pk)
            copyright_pk,
            UT.uploadtree_pk AS uploadtree_pk,
            (CASE WHEN (CE.content IS NULL OR CE.content = '') THEN C.content ELSE CE.content END) AS content,
            (CASE WHEN (CE.hash IS NULL OR CE.hash = '') THEN C.hash ELSE CE.hash END) AS hash,
            C.agent_fk AS agent_fk,
            C.is_enabled AS original_is_enabled,
            CE.is_enabled AS modified_is_enabled
        FROM copyright C
        INNER JOIN uploadtree UT on C.pfile_fk = UT.pfile_fk
        LEFT JOIN copyright_event CE ON CE.copyright_fk = C.copyright_pk
            AND CE.uploadtree_fk = UT.uploadtree_pk
        WHERE C.content IS NOT NULL
            AND C.content != ''
        ORDER BY copyright_pk, UT.uploadtree_pk, content DESC;
        """

        cursor.execute(sql)

        records = cursor.fetchall()
        #print(records)
        results = []
        for record in records:
            result = {
                "content": record[2],
                "is_enabled": record[5]
            }
            results.append(result)
        df = pd.DataFrame(results)



    except Exception as error:
        print(f"Error: {error}")
    finally:
        print(df)
        # Save the dataframe to a CSV file
        df.to_csv('copyrights.csv', index=False)
        if connection:
            cursor.close()
            connection.close()

__name__ == "__main__"
fetch_copyright_data()

