name: Retrain Model

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 18 * * *' # Runs daily at midnight

jobs:
  retrain_model:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install psycopg2 pandas
        pip install safaa
        pip install -r requirements.txt

    # Step 4: Run data retrieval script
    - name: Run data retrieval
      run: python retrieve_data.py

    # Step 5: Retrain model if needed
    - name: Retrain model
      run: python retrain_model.py

    # Step 6: Commit and push new model
    - name: Commit and push new model
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add models/updated_model.pkl
        git commit -m 'Retrain model with new data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
